[package]
name = "super-sideloader"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.8"
gpui = { package = "gpui", git = "https://github.com/gpui-ce/gpui-ce" }
gpui_platform = { git = "https://github.com/gpui-ce/gpui-ce", features = ["font-kit", "x11", "wayland", "runtime_shaders"] }
